import type { Metadata } from 'next';
import { Geist, Geist_Mono, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { cn } from '@/shared/lib/cn';
import AppAside from '@/widgets/Aside/ui/AppAside';
import Header from '@/widgets/Header/Header';
import SubHeader from '@/widgets/SubHeader/SubHeader';
import Providers from '@/app/_providers';
import { ReactNode } from 'react';

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className={cn('font-mono', jetbrainsMono.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <div className="flex h-screen max-w-full">
            <AppAside />
            <div className="flex w-full flex-col">
              <Header />
              <SubHeader />
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
