import type { Metadata } from 'next';
import { Geist, Geist_Mono, JetBrains_Mono } from 'next/font/google';
import '../shared/styles/global.css';
import { cn } from '@/shared/lib/cn';
import Providers from '@/app/_providers';
import { ReactNode } from 'react';
import { App } from '@/app/app';

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(geistSans.variable, jetbrainsMono.variable)}
      suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=JSON.parse(localStorage.getItem('theme-storage')||'{}');if(t.state&&t.state.theme==='dark'){document.documentElement.classList.add('dark')}}catch(e){}})();`,
          }}
        />
      </head>
      <body
        className={cn(geistSans.variable, geistMono.variable, 'antialiased')}>
        <Providers>
          <App children={children} />
        </Providers>
      </body>
    </html>
  );
}
